/* Generated By:JavaCC: Do not edit this line. ProgramScannerConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProgramScannerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 1;
  /** RegularExpression Id. */
  int UPPERCASE = 2;
  /** RegularExpression Id. */
  int LOWERCASE = 3;
  /** RegularExpression Id. */
  int END = 4;
  /** RegularExpression Id. */
  int LI = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<INTEGER>",
    "<UPPERCASE>",
    "<LOWERCASE>",
    "<END>",
    "<LI>",
  };

}
